import * as Icons from "phosphor-react";
import { IconEntry, IconCategory } from ".";

export const icons: ReadonlyArray<IconEntry> = [
  {
    name: "alien",
    category: IconCategory.GAMES,
    tags: [
      "*new*",
      "ufo",
      "space",
      "flying saucer",
      "extra terrestrial",
      "sci-fi",
    ],
    Icon: Icons.Alien,
  },
  {
    name: "align-bottom-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "flush bottom"],
    Icon: Icons.AlignBottomSimple,
  },
  {
    name: "align-center-horizontal-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "centered", "middle"],
    Icon: Icons.AlignCenterHorizontalSimple,
  },
  {
    name: "align-center-vertical-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "centered", "middle"],
    Icon: Icons.AlignCenterVerticalSimple,
  },
  {
    name: "align-left-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "flush left"],
    Icon: Icons.AlignLeftSimple,
  },
  {
    name: "align-right-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "flush right"],
    Icon: Icons.AlignRightSimple,
  },
  {
    name: "align-top-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "alignment", "arrangement", "layout", "flush top"],
    Icon: Icons.AlignTopSimple,
  },
  {
    name: "angular-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "framework", "javascript", "google", "web"],
    Icon: Icons.AngularLogo,
  },
  {
    name: "app-store-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "macintosh", "imac", "iphone", "ipad", "macos", "ios"],
    Icon: Icons.AppStoreLogo,
  },
  {
    name: "apple-podcasts-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "macintosh", "imac", "iphone", "ipad", "macos", "ios"],
    Icon: Icons.ApplePodcastsLogo,
  },
  {
    name: "arrows-horizontal",
    category: IconCategory.ARROWS,
    tags: [
      "*new*",
      "directional",
      "pointer",
      "cursor",
      "resize",
      "expand",
      "left",
      "right",
    ],
    Icon: Icons.ArrowsHorizontal,
  },
  {
    name: "arrows-vertical",
    category: IconCategory.ARROWS,
    tags: [
      "*new*",
      "directional",
      "pointer",
      "cursor",
      "resize",
      "expand",
      "up",
      "down",
    ],
    Icon: Icons.ArrowsVertical,
  },
  {
    name: "asterisk-simple",
    category: IconCategory.COMMUNICATION,
    tags: ["*new*", "star", "wildcard", "bullet point", "5", "emergency"],
    Icon: Icons.AsteriskSimple,
  },
  {
    name: "backpack",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "knapsack", "camping", "school", "bag"],
    Icon: Icons.Backpack,
  },
  {
    name: "balloon",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "helium", "birthday", "party"],
    Icon: Icons.Balloon,
  },
  {
    name: "barricade",
    category: IconCategory.MAP,
    tags: ["*new*", "construction", "safety", "gate"],
    Icon: Icons.Barricade,
  },
  {
    name: "bathtub",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "bath", "shower", "bathroom", "faucet"],
    Icon: Icons.Bathtub,
  },
  {
    name: "battery-plus",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "charged", "charger", "charging", "power"],
    Icon: Icons.BatteryPlus,
  },
  {
    name: "beer-bottle",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "drinks",
      "beverages",
      "places",
      "locations",
      "bars",
      "restaurants",
      "food",
      "dining",
    ],
    Icon: Icons.BeerBottle,
  },
  {
    name: "behance-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "logos", "illustration", "ui", "interface"],
    Icon: Icons.BehanceLogo,
  },
  {
    name: "bezier-curve",
    category: IconCategory.DESIGN,
    tags: ["*new*", "shapes", "drawing", "path", "pen"],
    Icon: Icons.BezierCurve,
  },
  {
    name: "binoculars",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "telescope", "glasses", "search", "find", "explore"],
    Icon: Icons.Binoculars,
  },
  {
    name: "butterfly",
    category: IconCategory.WEATHER,
    tags: ["*new*", "animals", "insects", "moth"],
    Icon: Icons.Butterfly,
  },
  {
    name: "cactus",
    category: IconCategory.WEATHER,
    tags: ["*new*", "plants", "cacti", "desert", "western"],
    Icon: Icons.Cactus,
  },
  {
    name: "camera-rotate",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "photography",
      "pictures",
      "orientation",
      "portrait",
      "landscape",
      "selfie",
    ],
    Icon: Icons.CameraRotate,
  },
  {
    name: "campfire",
    category: IconCategory.WEATHER,
    tags: ["*new*", "camping", "flame", "bonfire", "outdoors"],
    Icon: Icons.Campfire,
  },
  {
    name: "circle-notch",
    category: IconCategory.DESIGN,
    tags: [
      "*new*",
      "round",
      "shapes",
      "loading",
      "loader",
      "spinner",
      "waiting",
      "progress",
    ],
    Icon: Icons.CircleNotch,
  },
  {
    name: "coat-hanger",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "clothing", "clothes", "closet"],
    Icon: Icons.CoatHanger,
  },
  {
    name: "codepen-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "ide", "logos"],
    Icon: Icons.CodepenLogo,
  },
  {
    name: "codesandbox-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "ide", "logos"],
    Icon: Icons.CodesandboxLogo,
  },
  {
    name: "coin-vertical",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "cents",
      "change",
      "money",
      "currency",
      "payment",
      "paying",
      "purchase",
      "price",
      "sell",
    ],
    Icon: Icons.CoinVertical,
  },
  {
    name: "coins",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "cents",
      "change",
      "money",
      "currency",
      "payment",
      "paying",
      "purchase",
      "price",
      "sell",
    ],
    Icon: Icons.Coins,
  },
  {
    name: "confetti",
    category: IconCategory.GAMES,
    tags: ["*new*", "tada", "party", "emoji"],
    Icon: Icons.Confetti,
  },
  {
    name: "copyleft",
    category: IconCategory.MEDIA,
    tags: ["*new*", "🄯", "intellectual property", "copr.", "symbol"],
    Icon: Icons.Copyleft,
  },
  {
    name: "currency-eth",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "money",
      "ethereum",
      "crypto",
      "cryptocurrency",
      "payment",
      "paying",
      "purchase",
    ],
    Icon: Icons.CurrencyEth,
  },
  {
    name: "currency-kzt",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "money",
      "kazakhstan",
      "tenge",
      "payment",
      "paying",
      "purchase",
    ],
    Icon: Icons.CurrencyKzt,
  },
  {
    name: "currency-ngn",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "money",
      "nigeria",
      "naira",
      "payment",
      "paying",
      "purchase",
    ],
    Icon: Icons.CurrencyNgn,
  },
  {
    name: "cursor-text",
    category: IconCategory.OFFICE,
    tags: ["*new*", "i-beam", "input", "select"],
    Icon: Icons.CursorText,
  },
  {
    name: "cylinder",
    category: IconCategory.DESIGN,
    tags: ["*new*", "shapes", "tube"],
    Icon: Icons.Cylinder,
  },
  {
    name: "detective",
    category: IconCategory.SECURITY,
    tags: ["*new*", "incognito", "police", "law enforcement", "spy", "secret"],
    Icon: Icons.Detective,
  },
  {
    name: "diamonds-four",
    category: IconCategory.DESIGN,
    tags: ["*new*", "shapes", "grid"],
    Icon: Icons.DiamondsFour,
  },
  {
    name: "drop-half-bottom",
    category: IconCategory.DESIGN,
    tags: [
      "*new*",
      "droplet",
      "teardrop",
      "raindrop",
      "humidity",
      "water",
      "contrast",
      "brightness",
    ],
    Icon: Icons.DropHalfBottom,
  },
  {
    name: "egg",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "chicken", "food", "meal", "baby", "hatch"],
    Icon: Icons.Egg,
  },
  {
    name: "egg-crack",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "chicken", "food", "meal", "baby", "hatch", "break"],
    Icon: Icons.EggCrack,
  },
  {
    name: "equalizer",
    category: IconCategory.MEDIA,
    tags: ["*new*", "music", "audio", "meter", "volume", "spectrum", "eq"],
    Icon: Icons.Equalizer,
  },
  {
    name: "exam",
    category: IconCategory.EDUCATION,
    tags: ["*new*", "text", "examination", "paper", "school", "grade"],
    Icon: Icons.Exam,
  },
  {
    name: "eyedropper-sample",
    category: IconCategory.DESIGN,
    tags: ["*new*", "colors", "color picker", "arts"],
    Icon: Icons.EyedropperSample,
  },
  {
    name: "eyeglasses",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "vision", "spectacles"],
    Icon: Icons.Eyeglasses,
  },
  {
    name: "file-audio",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "music", "sound"],
    Icon: Icons.FileAudio,
  },
  {
    name: "file-cloud",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "sync"],
    Icon: Icons.FileCloud,
  },
  {
    name: "file-code",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents"],
    Icon: Icons.FileCode,
  },
  {
    name: "file-css",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code"],
    Icon: Icons.FileCss,
  },
  {
    name: "file-csv",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "data"],
    Icon: Icons.FileCsv,
  },
  {
    name: "file-doc",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "word", "microsoft"],
    Icon: Icons.FileDoc,
  },
  {
    name: "file-html",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code"],
    Icon: Icons.FileHtml,
  },
  {
    name: "file-image",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "pictures", "photograph"],
    Icon: Icons.FileImage,
  },
  {
    name: "file-jpg",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "pictures", "photograph", "jpeg"],
    Icon: Icons.FileJpg,
  },
  {
    name: "file-js",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code", "javascript"],
    Icon: Icons.FileJs,
  },
  {
    name: "file-jsx",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code", "javascript"],
    Icon: Icons.FileJsx,
  },
  {
    name: "file-lock",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "secure", "locked", "private"],
    Icon: Icons.FileLock,
  },
  {
    name: "file-png",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "pictures", "photograph"],
    Icon: Icons.FilePng,
  },
  {
    name: "file-ppt",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "powerpoint", "microsoft"],
    Icon: Icons.FilePpt,
  },
  {
    name: "file-rs",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code", "rust"],
    Icon: Icons.FileRs,
  },
  {
    name: "file-ts",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code", "typescript"],
    Icon: Icons.FileTs,
  },
  {
    name: "file-tsx",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code", "typescript"],
    Icon: Icons.FileTsx,
  },
  {
    name: "file-video",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "movie"],
    Icon: Icons.FileVideo,
  },
  {
    name: "file-vue",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "code"],
    Icon: Icons.FileVue,
  },
  {
    name: "file-xls",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "excel", "microsoft"],
    Icon: Icons.FileXls,
  },
  {
    name: "file-zip",
    category: IconCategory.OFFICE,
    tags: ["*new*", "documents", "archive", "compression"],
    Icon: Icons.FileZip,
  },
  {
    name: "film-script",
    category: IconCategory.MEDIA,
    tags: ["*new*", "screenplay", "movie"],
    Icon: Icons.FilmScript,
  },
  {
    name: "film-slate",
    category: IconCategory.MEDIA,
    tags: ["*new*", "clapper", "movie"],
    Icon: Icons.FilmSlate,
  },
  {
    name: "flag-checkered",
    category: IconCategory.GAMES,
    tags: ["*new*", "flags", "race", "racing", "finish line"],
    Icon: Icons.FlagCheckered,
  },
  {
    name: "flying-saucer",
    category: IconCategory.GAMES,
    tags: ["*new*", "ufo", "space", "aliens", "extra terrestrial", "sci-fi"],
    Icon: Icons.FlyingSaucer,
  },
  {
    name: "folder-dotted",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "missing",
      "temporary",
    ],
    Icon: Icons.FolderDotted,
  },
  {
    name: "folder-lock",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "private",
      "secure",
    ],
    Icon: Icons.FolderLock,
  },
  {
    name: "folder-simple-dotted",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "missing",
      "temporary",
    ],
    Icon: Icons.FolderSimpleDotted,
  },
  {
    name: "folder-simple-lock",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "private",
      "secure",
    ],
    Icon: Icons.FolderSimpleLock,
  },
  {
    name: "folder-simple-star",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "favorite",
      "starred",
    ],
    Icon: Icons.FolderSimpleStar,
  },
  {
    name: "folder-simple-user",
    category: IconCategory.OFFICE,
    tags: ["*new*", "directory", "directories", "files", "folders", "personal"],
    Icon: Icons.FolderSimpleUser,
  },
  {
    name: "folder-star",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "directory",
      "directories",
      "files",
      "folders",
      "favorite",
      "starred",
    ],
    Icon: Icons.FolderStar,
  },
  {
    name: "folder-user",
    category: IconCategory.OFFICE,
    tags: ["*new*", "directory", "directories", "files", "folders", "personal"],
    Icon: Icons.FolderUser,
  },
  {
    name: "function",
    category: IconCategory.FINANCE,
    tags: ["*new*", "mathematics", "arithmetic"],
    Icon: Icons.Function,
  },
  {
    name: "google-chrome-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "web browsers", "internet"],
    Icon: Icons.GoogleChromeLogo,
  },
  {
    name: "google-photos-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "album", "pictures", "photography"],
    Icon: Icons.GooglePhotosLogo,
  },
  {
    name: "google-podcasts-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "audio"],
    Icon: Icons.GooglePodcastsLogo,
  },
  {
    name: "gradient",
    category: IconCategory.DESIGN,
    tags: ["*new*", "fade", "ombre", "opacity"],
    Icon: Icons.Gradient,
  },
  {
    name: "graph",
    category: IconCategory.FINANCE,
    tags: ["*new*", "nodes", "tree"],
    Icon: Icons.Graph,
  },
  {
    name: "hamburger",
    category: IconCategory.COMMERCE,
    tags: [
      "*new*",
      "fast food",
      "party",
      "places",
      "locations",
      "restaurants",
      "food",
      "dining",
    ],
    Icon: Icons.Hamburger,
  },
  {
    name: "hand-eye",
    category: IconCategory.PEOPLE,
    tags: ["*new*", "pointers", "cursors", "emoji", "hamsa", "evil eye"],
    Icon: Icons.HandEye,
  },
  {
    name: "heart-break",
    category: IconCategory.GAMES,
    tags: ["*new*", "love", "hate", "crack", "split", "divorce", "emoji"],
    Icon: Icons.HeartBreak,
  },
  {
    name: "heart-straight-break",
    category: IconCategory.GAMES,
    tags: ["*new*", "love", "hate", "crack", "split", "divorce", "emoji"],
    Icon: Icons.HeartStraightBreak,
  },
  {
    name: "kanban",
    category: IconCategory.OFFICE,
    tags: [
      "*new*",
      "scheduling",
      "tasks",
      "project management",
      "process",
      "lean",
      "agile",
    ],
    Icon: Icons.Kanban,
  },
  {
    name: "keyhole",
    category: IconCategory.SECURITY,
    tags: [
      "*new*",
      "lock",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "encrypted",
      "encryption",
      "privacy",
      "private",
    ],
    Icon: Icons.Keyhole,
  },
  {
    name: "ladder",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "stairs", "steps", "climbing"],
    Icon: Icons.Ladder,
  },
  {
    name: "ladder-simple",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "stairs", "steps", "climbing"],
    Icon: Icons.LadderSimple,
  },
  {
    name: "linux-logo",
    category: IconCategory.DEVELOPMENT,
    tags: ["*new*", "penguin", "computer", "animals"],
    Icon: Icons.LinuxLogo,
  },
  {
    name: "list-checks",
    category: IconCategory.OFFICE,
    tags: ["*new*", "checklist", "todo"],
    Icon: Icons.ListChecks,
  },
  {
    name: "mask-happy",
    category: IconCategory.GAMES,
    tags: ["*new*", "theater", "costume", "smile", "smiling", "thalia"],
    Icon: Icons.MaskHappy,
  },
  {
    name: "mask-sad",
    category: IconCategory.GAMES,
    tags: ["*new*", "theater", "costume", "cry", "crying", "melpomene"],
    Icon: Icons.MaskSad,
  },
  {
    name: "microphone-stage",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "audio",
      "recording",
      "music",
      "sound",
      "performance",
      "concert",
    ],
    Icon: Icons.MicrophoneStage,
  },
  {
    name: "microsoft-excel-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "tables", "spreadsheets", "tabular"],
    Icon: Icons.MicrosoftExcelLogo,
  },
  {
    name: "microsoft-powerpoint-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "slides", "slideshow", "presentation"],
    Icon: Icons.MicrosoftPowerpointLogo,
  },
  {
    name: "microsoft-teams-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "chat", "video conference"],
    Icon: Icons.MicrosoftTeamsLogo,
  },
  {
    name: "microsoft-word-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "documents", "word processor", "doc", "docx"],
    Icon: Icons.MicrosoftWordLogo,
  },
  {
    name: "mountains",
    category: IconCategory.WEATHER,
    tags: ["*new*", "hills", "outdoors", "terrain", "geology", "adventure"],
    Icon: Icons.Mountains,
  },
  {
    name: "music-notes-plus",
    category: IconCategory.MEDIA,
    tags: ["*new*", "songs", "audio", "playlist", "albums", "add"],
    Icon: Icons.MusicNotesPlus,
  },
  {
    name: "needle",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "sewing", "thread", "awl", "tailor"],
    Icon: Icons.Needle,
  },
  {
    name: "option",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "keyboard", "shortcut", "modifier"],
    Icon: Icons.Option,
  },
  {
    name: "parachute",
    category: IconCategory.MAP,
    tags: ["*new*", "skydiving", "safety"],
    Icon: Icons.Parachute,
  },
  {
    name: "password",
    category: IconCategory.SECURITY,
    tags: [
      "*new*",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "login",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icons.Password,
  },
  {
    name: "pencil-simple-line",
    category: IconCategory.DESIGN,
    tags: ["*new*", "write", "writing", "editing", "sign", "signature"],
    Icon: Icons.PencilSimpleLine,
  },
  {
    name: "perspective",
    category: IconCategory.DESIGN,
    tags: ["*new*", "3d", "skew", "warp", "trapezoid"],
    Icon: Icons.Perspective,
  },
  {
    name: "piano-keys",
    category: IconCategory.MEDIA,
    tags: ["*new*", "music", "instrument", "keyboard"],
    Icon: Icons.PianoKeys,
  },
  {
    name: "pinwheel",
    category: IconCategory.GAMES,
    tags: ["*new*", "toys", "whirligig"],
    Icon: Icons.Pinwheel,
  },
  {
    name: "plug",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "outlet", "socket", "plugin", "integration"],
    Icon: Icons.Plug,
  },
  {
    name: "plugs",
    category: IconCategory.SYSTEM,
    tags: [
      "*new*",
      "outlet",
      "socket",
      "plugin",
      "integration",
      "disconnected",
    ],
    Icon: Icons.Plugs,
  },
  {
    name: "plugs-connected",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "outlet", "socket", "plugin", "integration"],
    Icon: Icons.PlugsConnected,
  },
  {
    name: "police-car",
    category: IconCategory.MAP,
    tags: ["*new*", "vehicles", "cars", "automobiles", "law enforcement"],
    Icon: Icons.PoliceCar,
  },
  {
    name: "popcorn",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "food", "movies", "theater"],
    Icon: Icons.Popcorn,
  },
  {
    name: "radio-button",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "input", "checkbox", "checked"],
    Icon: Icons.RadioButton,
  },
  {
    name: "rug",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "tapestry", "carpet"],
    Icon: Icons.Rug,
  },
  {
    name: "scan",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "upc", "barcode", "products", "shopping", "scanner"],
    Icon: Icons.Scan,
  },
  {
    name: "scroll",
    category: IconCategory.GAMES,
    tags: ["*new*", "parchment", "paper", "script", "spell", "fantasy"],
    Icon: Icons.Scroll,
  },
  {
    name: "shield-star",
    category: IconCategory.SECURITY,
    tags: [
      "*new*",
      "badge",
      "security",
      "defense",
      "authentication",
      "authenticated",
      "guarded",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icons.ShieldStar,
  },
  {
    name: "sidebar",
    category: IconCategory.DESIGN,
    tags: ["*new*", "left rail", "wireframe", "ui", "interface"],
    Icon: Icons.Sidebar,
  },
  {
    name: "sidebar-simple",
    category: IconCategory.DESIGN,
    tags: ["*new*", "left rail", "wireframe", "ui", "interface"],
    Icon: Icons.SidebarSimple,
  },
  {
    name: "signpost",
    category: IconCategory.MAP,
    tags: [
      "*new*",
      "direction",
      "traffic",
      "road sign",
      "transit",
      "transportation",
    ],
    Icon: Icons.Signpost,
  },
  {
    name: "skull",
    category: IconCategory.GAMES,
    tags: ["*new*", "death", "dead", "kill"],
    Icon: Icons.Skull,
  },
  {
    name: "spiral",
    category: IconCategory.GAMES,
    tags: ["*new*", "spin", "rotate", "dizzy"],
    Icon: Icons.Spiral,
  },
  {
    name: "square-half-bottom",
    category: IconCategory.DESIGN,
    tags: [
      "*new*",
      "4",
      "shapes",
      "polygons",
      "box",
      "columns",
      "sidebar",
      "split vertical",
    ],
    Icon: Icons.SquareHalfBottom,
  },
  {
    name: "stack-overflow-logo",
    category: IconCategory.BRAND,
    tags: ["*new*", "logos", "code"],
    Icon: Icons.StackOverflowLogo,
  },
  {
    name: "stamp",
    category: IconCategory.DESIGN,
    tags: ["*new*", "clone", "seal", "official"],
    Icon: Icons.Stamp,
  },
  {
    name: "strategy",
    category: IconCategory.GAMES,
    tags: ["*new*", "sports", "strategem", "plan", "tic-tac-toe"],
    Icon: Icons.Strategy,
  },
  {
    name: "sunglasses",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "vision", "sun", "spectacles"],
    Icon: Icons.Sunglasses,
  },
  {
    name: "syringe",
    category: IconCategory.HEALTH,
    tags: [
      "*new*",
      "needle",
      "vaccine",
      "medicine",
      "doctor",
      "shot",
      "hospital",
    ],
    Icon: Icons.Syringe,
  },
  {
    name: "tabs",
    category: IconCategory.SYSTEM,
    tags: ["*new*", "browser", "window", "folders", "files"],
    Icon: Icons.Tabs,
  },
  {
    name: "taxi",
    category: IconCategory.MAP,
    tags: [
      "*new*",
      "vehicles",
      "cars",
      "automobiles",
      "livery",
      "limousine",
      "uber",
    ],
    Icon: Icons.Taxi,
  },
  {
    name: "text-indent",
    category: IconCategory.OFFICE,
    tags: ["*new*", "alignment", "tab"],
    Icon: Icons.TextIndent,
  },
  {
    name: "text-outdent",
    category: IconCategory.OFFICE,
    tags: ["*new*", "alignment", "tab", "unindent", "dedent"],
    Icon: Icons.TextOutdent,
  },
  {
    name: "textbox",
    category: IconCategory.OFFICE,
    tags: ["*new*", "input", "cursor", "field"],
    Icon: Icons.Textbox,
  },
  {
    name: "toilet",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "bathroom", "restroom", "lavatory", "water closet"],
    Icon: Icons.Toilet,
  },
  {
    name: "trademark-registered",
    category: IconCategory.COMMERCE,
    tags: ["*new*", "®", "™", "intellectual property"],
    Icon: Icons.TrademarkRegistered,
  },
  {
    name: "traffic-cone",
    category: IconCategory.MAP,
    tags: ["*new*", "pylon", "safety", "transit", "transportation"],
    Icon: Icons.TrafficCone,
  },
  {
    name: "traffic-signal",
    category: IconCategory.MAP,
    tags: ["*new*", "stop light", "safety", "transit", "transportation"],
    Icon: Icons.TrafficSignal,
  },
  {
    name: "user-switch",
    category: IconCategory.PEOPLE,
    tags: [
      "*new*",
      "person",
      "users",
      "profile",
      "account",
      "login",
      "logout",
      "signin",
      "signout",
      "settings",
      "preferences",
    ],
    Icon: Icons.UserSwitch,
  },
  {
    name: "vault",
    category: IconCategory.SECURITY,
    tags: [
      "*new*",
      "safe",
      "bank",
      "security",
      "secured",
      "authentication",
      "authenticated",
      "locked",
      "encrypted",
      "encryption",
    ],
    Icon: Icons.Vault,
  },
  {
    name: "vignette",
    category: IconCategory.DESIGN,
    tags: ["*new*", "photography", "darkroom", "movie", "analog"],
    Icon: Icons.Vignette,
  },
  {
    name: "wave-sawtooth",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "synth",
      "synthesizer",
      "sound",
      "audio",
      "music",
      "waveform",
    ],
    Icon: Icons.WaveSawtooth,
  },
  {
    name: "wave-sine",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "synth",
      "synthesizer",
      "sound",
      "audio",
      "music",
      "waveform",
    ],
    Icon: Icons.WaveSine,
  },
  {
    name: "wave-square",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "synth",
      "synthesizer",
      "sound",
      "audio",
      "music",
      "waveform",
    ],
    Icon: Icons.WaveSquare,
  },
  {
    name: "wave-triangle",
    category: IconCategory.MEDIA,
    tags: [
      "*new*",
      "synth",
      "synthesizer",
      "sound",
      "audio",
      "music",
      "waveform",
    ],
    Icon: Icons.WaveTriangle,
  },
  {
    name: "webcam",
    category: IconCategory.MEDIA,
    tags: ["*new*", "camera", "video conference"],
    Icon: Icons.Webcam,
  },
  {
    name: "yin-yang",
    category: IconCategory.COMMUNICATION,
    tags: ["*new*", "symbol", "good", "evil", "black", "white"],
    Icon: Icons.YinYang,
  },
];

if (process.env.NODE_ENV === "development") {
  console.log(`${icons.length} icons`);
}

export const iconCount = (icons.length * 6)
  .toString()
  .replace(/B(?=(d{3})+(?!d))/g, ",");
